[tool.poetry]
name = "lab0-sandbox-rawanali1993"
version = "0.1.0"
description = ""
authors = ["RawanAli1993 <rawan.08.ali@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
