name: lab-0

# add your pipline description below

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7.1'
      - name: Install dependencies
        run: poetry install; poetry add pytest
      - name: Run pytest
        run: poetry run pytest .